# .github/workflows/build.yaml
name: build
on: [push, pull_request]

jobs:
  job-build-fract-ol:
    runs-on: ubuntu-latest
    name: Build fract-ol
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: make fract-ol
      working-directory: ./fract-ol
      run: make re
